name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello, world!"
      - name: Step 2
        run: echo "This is another step."
